services:
  app:
    container_name: cardinalsixcyber
    build:
      context: .
    image: cardinalsixcyber:local
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
