NOTES = {
    # =========================================================================
    # CONFIGURATION MANAGEMENT (CM) — 9 practices
    # =========================================================================

    "cm-l1-3-4-1": (
        '<p>A baseline configuration is basically a snapshot of how your systems are set up '
        'right now — what software is installed, what settings are active, what hardware is '
        'in place. Think of it as your "known good" starting point. If something goes wrong '
        'or changes unexpectedly, you compare back to the baseline to figure out what moved.</p>'
        '<p>You need to keep this documented and update it whenever you make changes — new '
        'software installs, patches, hardware swaps, or configuration tweaks.</p>'
        '<p><strong>Example 1:</strong> Use Microsoft Endpoint Configuration Manager (MECM/SCCM) '
        'to run a hardware and software inventory scan across all endpoints. Export the baseline '
        'report from <em>Assets and Compliance &gt; Overview &gt; Device Collections</em> and '
        'store it in your configuration management repository. Re-run and compare after each '
        'change window.</p>'
        '<p><strong>Example 2:</strong> In a smaller environment, maintain a baseline spreadsheet '
        'or use a tool like Nessus to run a credentialed scan. Under <em>Scans &gt; New Scan &gt; '
        'Advanced Scan &gt; Discovery</em>, enable host enumeration and software inventory plugins. '
        'Save the scan results as your documented baseline and schedule quarterly re-scans.</p>'
    ),

    "cm-l1-3-4-2": (
        '<p>This practice is about making sure your systems are locked down to their most '
        'restrictive settings that still let people do their jobs. You document those settings, '
        'and if anyone needs an exception — say, opening an extra port or enabling a service — '
        'that deviation gets formally approved and written down.</p>'
        '<p>The key idea: start tight, loosen only where justified, and document every exception.</p>'
        '<p><strong>Example 1:</strong> Apply DISA STIGs through Group Policy. In the Group '
        'Policy Management Console, navigate to <em>Computer Configuration &gt; Policies &gt; '
        'Administrative Templates &gt; Windows Components</em> and import the relevant STIG GPO '
        'backup. For any settings your operations require you to deviate from, document the '
        'finding ID, justification, and approving authority in a Plan of Action and Milestones (POA&M).</p>'
        '<p><strong>Example 2:</strong> In the M365 Admin Center, go to <em>Settings &gt; Org '
        'Settings &gt; Security &amp; Privacy</em> and disable external sharing in SharePoint unless '
        'explicitly approved. Document the restrictive default and any tenant-level exceptions '
        'in your System Security Plan (SSP).</p>'
    ),

    "cm-l2-3-4-3": (
        '<p>Configuration change control means you have a process for proposing, reviewing, '
        'approving, and documenting any change to your systems. Nobody should be making changes '
        'on the fly without someone checking whether that change could open a security hole.</p>'
        '<p>This applies to software updates, firewall rule changes, new user permissions — '
        'anything that alters how the system works.</p>'
        '<p><strong>Example 1:</strong> Use a change management board (even a simple one) and '
        'track requests in a ticketing system like Jira or ServiceNow. Create a workflow where '
        'each change request includes a security impact field. Route tickets through '
        '<em>Change Management &gt; Change Advisory Board (CAB)</em> for review before any '
        'production changes are made.</p>'
        '<p><strong>Example 2:</strong> For firewall changes, use Palo Alto Panorama or a '
        'similar management platform to stage rule changes in a <em>candidate configuration</em> '
        'before committing. Enable the audit log under <em>Device &gt; Setup &gt; Operations &gt; '
        'Audit Logging</em> so every proposed and committed change is tracked with the user who '
        'made it and a timestamp.</p>'
    ),

    "cm-l2-3-4-4": (
        '<p>Before you make any change to a system, you need to think through how it could '
        'affect security. Will this patch break an existing security control? Will opening '
        'this port expose something sensitive? After the change goes in, you verify that your '
        'security posture is still intact.</p>'
        '<p>This is about looking before you leap — and checking after you land.</p>'
        '<p><strong>Example 1:</strong> Before applying a Windows update or configuration change, '
        'run a vulnerability scan with Tenable Nessus or Tenable.sc. After the change, re-scan '
        'the same targets and compare results using the <em>Scan Comparison</em> report under '
        '<em>Reports &gt; Report Templates</em> to confirm no new vulnerabilities were introduced.</p>'
        '<p><strong>Example 2:</strong> In your change request ticket, include a mandatory '
        '"Security Impact Analysis" field that requires the requester to assess whether the '
        'change affects access controls, encryption, logging, or network segmentation. Use a '
        'checklist template tied to NIST 800-53 control families (AC, AU, SC, etc.) so nothing '
        'gets overlooked.</p>'
    ),

    "cm-l2-3-4-5": (
        '<p>Only authorized people should be able to make changes to your systems. This means '
        'both physical restrictions (who can walk up to a server and plug something in) and '
        'logical restrictions (who has admin credentials to modify configurations).</p>'
        '<p>If everyone can make changes, nobody is accountable — and you cannot trace what went '
        'wrong when something breaks.</p>'
        '<p><strong>Example 1:</strong> In Active Directory, restrict membership in privileged '
        'groups (Domain Admins, Enterprise Admins, Schema Admins) to only the personnel who '
        'genuinely need that access. Navigate to <em>Active Directory Users and Computers &gt; '
        'Builtin / Users</em> and audit group membership quarterly. Use a GPO to enforce '
        '<em>Restricted Groups</em> under <em>Computer Configuration &gt; Windows Settings &gt; '
        'Security Settings &gt; Restricted Groups</em>.</p>'
        '<p><strong>Example 2:</strong> For network infrastructure changes, configure role-based '
        'access control (RBAC) on your switches and routers. On Cisco IOS devices, use '
        '<code>privilege exec level 7</code> to create a custom privilege level that allows '
        'monitoring but not configuration changes. Reserve level 15 for approved network '
        'administrators only and log all access via a TACACS+ server.</p>'
    ),

    "cm-l2-3-4-6": (
        '<p>Your systems should only be running the software, services, and functions they '
        'actually need to do their job. Everything else is attack surface — unnecessary services, '
        'open ports, and unused protocols give attackers more ways in.</p>'
        '<p>Review regularly and turn off anything that is not mission-essential.</p>'
        '<p><strong>Example 1:</strong> On Windows servers, open <em>Server Manager &gt; Manage &gt; '
        'Remove Roles and Features</em> and strip out any roles not required for the server\'s '
        'function. A domain controller does not need the Print Server role, for instance. Also '
        'review <em>Services.msc</em> and disable services like <em>Xbox Live Auth Manager</em> '
        'or <em>Fax</em> that have no business on a server.</p>'
        '<p><strong>Example 2:</strong> On your perimeter firewall, run a port audit. In Palo '
        'Alto, go to <em>Policies &gt; Security</em> and review each allow rule. Use the '
        '<em>Rule Usage</em> statistics (visible in Panorama under <em>Policies &gt; Rule Usage</em>) '
        'to identify rules with zero hits over the past 90 days. Disable or remove unused rules '
        'and document the cleanup.</p>'
    ),

    "cm-l2-3-4-7": (
        '<p>This practice reinforces the "least functionality" concept: actively restrict, '
        'disable, or prevent anything nonessential from running on your systems. Think of it '
        'as the enforcement arm of CM.L2-3.4.6 — you identified what is unnecessary, now you '
        'block it.</p>'
        '<p><strong>Example 1:</strong> Use Windows Defender Application Control (WDAC) or '
        'AppLocker to block unauthorized executables. In Group Policy, navigate to <em>Computer '
        'Configuration &gt; Windows Settings &gt; Security Settings &gt; Application Control '
        'Policies &gt; AppLocker</em>. Create default rules that allow Windows and Program Files '
        'paths, then add explicit deny rules for user-writable directories like '
        '<code>%TEMP%</code> and <code>%APPDATA%</code>.</p>'
        '<p><strong>Example 2:</strong> On Linux systems, use <code>systemctl list-unit-files '
        '--type=service</code> to identify all enabled services. Disable nonessential ones with '
        '<code>systemctl disable --now [service]</code>. For ports, configure '
        '<code>firewalld</code> or <code>iptables</code> to drop all inbound traffic except '
        'explicitly allowed ports, and run <code>ss -tlnp</code> periodically to verify no '
        'unexpected listeners appear.</p>'
    ),

    "cm-l2-3-4-8": (
        '<p>This is application whitelisting — you keep a list of approved software, and '
        'everything else is blocked by default. Instead of trying to identify every bad program '
        '(which is impossible), you define what is allowed and deny everything else.</p>'
        '<p>This is one of the most effective controls you can implement against malware and '
        'unauthorized software.</p>'
        '<p><strong>Example 1:</strong> Deploy Windows Defender Application Control (WDAC) '
        'using Microsoft Intune. In the <em>Intune Admin Center &gt; Endpoint Security &gt; '
        'Application Control</em>, create a policy that allows only Microsoft-signed and '
        'your organization-signed applications. Start in audit mode to identify gaps, then '
        'switch to enforce mode once your authorized software list is finalized.</p>'
        '<p><strong>Example 2:</strong> Use a third-party tool like Carbon Black App Control '
        '(formerly Cb Protection). Define your approved software list in the management console '
        'under <em>Rules &gt; Software Rules</em>. Set the enforcement level to "High" so only '
        'approved publishers and file hashes can execute. Review the "Unapproved Files" report '
        'monthly to update the list as legitimate new software is deployed.</p>'
    ),

    "cm-l2-3-4-9": (
        '<p>Users should not be able to install whatever they want on company systems. '
        'Uncontrolled software installs bring in security risks — unlicensed tools, vulnerable '
        'applications, even malware disguised as legitimate programs.</p>'
        '<p>You need a policy that governs what users can install, plus technical controls to '
        'enforce it.</p>'
        '<p><strong>Example 1:</strong> In Microsoft Intune, go to <em>Devices &gt; Configuration '
        'Profiles</em> and create a Device Restrictions profile. Under <em>General &gt; Block '
        'the installation of apps from unknown sources</em>, set it to block. For Windows, '
        'also configure <em>SmartScreen</em> to warn or block unrecognized apps via '
        '<em>Endpoint Security &gt; Attack Surface Reduction</em>.</p>'
        '<p><strong>Example 2:</strong> Remove local administrator rights from standard user '
        'accounts via Group Policy. Navigate to <em>Computer Configuration &gt; Windows Settings '
        '&gt; Security Settings &gt; Restricted Groups</em> and ensure only IT-approved accounts '
        'are members of the local Administrators group. Without admin rights, users cannot '
        'install most software on their own, and any legitimate requests route through your '
        'IT helpdesk with proper approval.</p>'
    ),

    # =========================================================================
    # IDENTIFICATION & AUTHENTICATION (IA) — 11 practices
    # =========================================================================

    "ia-l1-3-5-1": (
        '<p>Every person who uses your systems needs their own unique account — no shared '
        'logins, no generic "admin" accounts that three people use. When someone does something '
        'on the system, you need to be able to trace it back to exactly who did it.</p>'
        '<p>This is foundational. Without unique identification, your audit logs are meaningless.</p>'
        '<p><strong>Example 1:</strong> In Active Directory, ensure every employee has a uniquely '
        'named account (e.g., <code>jsmith</code> or <code>jane.smith</code>). Disable or rename '
        'default accounts: go to <em>Computer Configuration &gt; Windows Settings &gt; Security '
        'Settings &gt; Local Policies &gt; Security Options</em> and set "Accounts: Rename '
        'administrator account" and "Accounts: Rename guest account" to non-obvious names.</p>'
        '<p><strong>Example 2:</strong> In M365 Admin Center, navigate to <em>Users &gt; Active '
        'Users</em> and verify each user has a unique UPN (User Principal Name). Disable shared '
        'mailbox sign-in by selecting the shared mailbox, clicking <em>Mail &gt; Block sign-in</em>. '
        'If service accounts are needed, create dedicated accounts with descriptive names like '
        '<code>svc-backup@contoso.com</code> rather than reusing a person\'s credentials.</p>'
    ),

    "ia-l1-3-5-2": (
        '<p>This is about identifying and authenticating devices — not just people — before they '
        'connect to your network. You need to know what machines are on your network and verify '
        'they are authorized to be there.</p>'
        '<p>Rogue devices plugged into your network are a serious risk, especially in environments '
        'handling CUI.</p>'
        '<p><strong>Example 1:</strong> Implement 802.1X port-based authentication on your network '
        'switches. On Cisco switches, configure <code>dot1x system-auth-control</code> globally, '
        'then on each access port enable <code>authentication port-control auto</code>. Pair this '
        'with a RADIUS server (like Microsoft NPS or Cisco ISE) that checks machine certificates '
        'before granting network access.</p>'
        '<p><strong>Example 2:</strong> In Microsoft Entra ID (Azure AD), use Conditional Access '
        'policies to require device compliance. Go to <em>Entra Admin Center &gt; Protection &gt; '
        'Conditional Access &gt; New Policy</em>. Set the condition to require the device be '
        'marked as compliant in Intune before accessing company resources. This ensures only '
        'enrolled, managed devices can authenticate to your cloud services.</p>'
    ),

    "ia-l2-3-5-3": (
        '<p>Multi-factor authentication (MFA) means you need two different types of proof to '
        'log in — typically your password (something you know) plus a code from your phone or '
        'a hardware key (something you have). A password alone is not enough anymore.</p>'
        '<p>This applies to both privileged accounts (admins) and regular user accounts.</p>'
        '<p><strong>Example 1:</strong> In the M365 Admin Center, go to <em>Users &gt; Active Users '
        '&gt; Multi-factor authentication</em> (or use the Entra Admin Center under <em>Protection '
        '&gt; Authentication Methods</em>). Enable MFA for all users via a Conditional Access '
        'policy that requires MFA for all cloud apps. For stronger assurance, configure the '
        'policy to require phishing-resistant methods (FIDO2 keys or Windows Hello) for admin '
        'accounts.</p>'
        '<p><strong>Example 2:</strong> For on-premises systems, deploy Duo Security or RSA '
        'SecurID as an MFA solution. Install the Duo Authentication Proxy and configure it to '
        'integrate with your Active Directory. Apply Duo to VPN logins and RDP sessions by '
        'configuring the Duo RDP application on each server under <em>Applications &gt; Protect '
        'an Application &gt; Microsoft RDP</em>.</p>'
    ),

    "ia-l2-3-5-4": (
        '<p>Replay-resistant authentication means an attacker cannot capture your login '
        'credentials in transit and reuse them later to break in. Old protocols like NTLM are '
        'vulnerable to this. Modern protocols like Kerberos and time-based one-time passwords '
        '(TOTP) generate unique tokens for each session, so a captured token is useless.</p>'
        '<p><strong>Example 1:</strong> Enforce Kerberos authentication over NTLM in your domain. '
        'In Group Policy, navigate to <em>Computer Configuration &gt; Windows Settings &gt; '
        'Security Settings &gt; Local Policies &gt; Security Options</em>. Set "Network security: '
        'LAN Manager authentication level" to <strong>Send NTLMv2 response only. Refuse LM &amp; '
        'NTLM</strong>. This forces clients and servers to use Kerberos or at minimum NTLMv2, '
        'which includes challenge-response to resist replay.</p>'
        '<p><strong>Example 2:</strong> When configuring MFA, choose time-based one-time passwords '
        '(TOTP) via authenticator apps like Microsoft Authenticator or hardware tokens like '
        'YubiKeys. In the Entra Admin Center under <em>Protection &gt; Authentication Methods '
        '&gt; FIDO2 Security Key</em>, enable FIDO2 key registration. FIDO2 uses '
        'challenge-response cryptography, making replay attacks effectively impossible.</p>'
    ),

    "ia-l2-3-5-5": (
        '<p>Identifier management is about how you create, assign, and retire usernames and '
        'account IDs. Someone with authority needs to approve each new account. You should '
        'never reuse an old employee\'s username for a new person — that creates confusion in '
        'audit logs and potential access bleed.</p>'
        '<p><strong>Example 1:</strong> Create a formal account provisioning process in your '
        'IT ticketing system. Each new account request requires a ticket with supervisor '
        'approval before IT creates the account. In Active Directory, enforce a naming convention '
        '(e.g., <code>first.last</code>) and use the <em>Description</em> field to note the '
        'approving manager and ticket number. When employees depart, disable (do not delete) '
        'accounts and move them to a "Disabled Users" OU.</p>'
        '<p><strong>Example 2:</strong> In the Entra Admin Center, configure the <em>Identity '
        'Governance &gt; Access Reviews</em> feature to automatically prompt managers to review '
        'their team members\' access quarterly. For service accounts, use <em>Managed Identities</em> '
        'where possible (under <em>Entra ID &gt; Managed Identities</em>) so credentials are '
        'automatically rotated and the identity lifecycle is handled by the platform.</p>'
    ),

    "ia-l2-3-5-6": (
        '<p>If an account sits unused for a long time, it becomes a risk — a former employee\'s '
        'credentials could be compromised, or a forgotten service account could be exploited. '
        'This practice says: set a timer, and if an account is inactive past that threshold, '
        'disable it automatically.</p>'
        '<p><strong>Example 1:</strong> In Active Directory, use a PowerShell script with '
        '<code>Search-ADAccount -AccountInactive -TimeSpan 90.00:00:00</code> to find accounts '
        'inactive for 90 days. Schedule this as a weekly task via Task Scheduler that '
        'automatically disables matching accounts and logs the action. Review the output with '
        'your security team monthly.</p>'
        '<p><strong>Example 2:</strong> In the Entra Admin Center, go to <em>Identity Governance '
        '&gt; Access Reviews</em> and create a review for all users. Set the review to '
        'auto-apply results and remove access for users who have not signed in within your '
        'defined inactivity period. You can also check sign-in activity under <em>Users &gt; '
        'Sign-in Logs</em> and filter by "Last sign-in" to identify stale accounts.</p>'
    ),

    "ia-l1-3-5-7": (
        '<p>Password management is more than just "make it 14 characters." You need to check '
        'passwords against known-compromised lists, transmit them only over encrypted channels, '
        'store them hashed (never in plain text), and force users to change temporary passwords '
        'immediately.</p>'
        '<p>The days of requiring password changes every 60 days are over — modern guidance says '
        'use strong, unique passwords and check them against breach databases instead.</p>'
        '<p><strong>Example 1:</strong> In Entra ID, enable <em>Password Protection</em> under '
        '<em>Protection &gt; Authentication Methods &gt; Password Protection</em>. Turn on '
        '"Enforce custom banned password list" and add company-specific terms. Also enable '
        '"Enable password protection on Windows Server Active Directory" to extend this to '
        'on-prem AD. This checks passwords against Microsoft\'s global banned list plus your '
        'custom list at every password change.</p>'
        '<p><strong>Example 2:</strong> Configure a Group Policy for password complexity under '
        '<em>Computer Configuration &gt; Windows Settings &gt; Security Settings &gt; Account '
        'Policies &gt; Password Policy</em>. Set minimum password length to 14 characters, '
        'enable "Password must meet complexity requirements," and set "Minimum password age" '
        'to 1 day (to prevent rapid cycling). Pair this with a tool like Specops Password '
        'Policy that checks new passwords against the Have I Been Pwned breach database in '
        'real time.</p>'
    ),

    "ia-l2-3-5-8": (
        '<p>This extends replay-resistant authentication specifically to non-privileged '
        '(regular user) accounts accessing the network. Even standard users need protections '
        'against attackers capturing and replaying their login sessions.</p>'
        '<p>If you have already implemented strong MFA and disabled legacy protocols for all '
        'accounts (not just admins), you are well on your way.</p>'
        '<p><strong>Example 1:</strong> In the Entra Admin Center, create a Conditional Access '
        'policy under <em>Protection &gt; Conditional Access</em> that targets all users (not '
        'just admins). Set the grant control to require MFA with an authentication strength of '
        '"Phishing-resistant MFA." This ensures even standard user accounts use tokens that '
        'cannot be replayed.</p>'
        '<p><strong>Example 2:</strong> On your VPN appliance (e.g., Cisco AnyConnect), configure '
        'certificate-based authentication combined with TOTP. In the ASA configuration, set '
        '<code>tunnel-group DefaultWEBVPNGroup webvpn-attributes</code> and configure '
        '<code>authentication certificate</code> along with a secondary authentication source '
        'pointed to your RADIUS/MFA server. This provides two layers of replay-resistant '
        'authentication for every remote user session.</p>'
    ),

    "ia-l2-3-5-9": (
        '<p>When you give someone a temporary password — for a new account or after a password '
        'reset — the system should force them to change it on their first login. A temporary '
        'password is a known shared secret between IT and the user, so it should not persist '
        'any longer than absolutely necessary.</p>'
        '<p><strong>Example 1:</strong> In Active Directory Users and Computers, when resetting '
        'a user\'s password, check the box <em>"User must change password at next logon."</em> '
        'This is a checkbox directly on the password reset dialog. Make it a standard operating '
        'procedure that your helpdesk always checks this box — never skip it.</p>'
        '<p><strong>Example 2:</strong> In the M365 Admin Center under <em>Users &gt; Active '
        'Users</em>, select the user and click <em>Reset Password</em>. Ensure the toggle '
        '"Require this user to change their password when they first sign in" is set to '
        '<strong>On</strong>. For bulk operations via PowerShell, use '
        '<code>Set-MsolUserPassword -UserPrincipalName user@contoso.com -ForceChangePassword '
        '$true</code>.</p>'
    ),

    "ia-l2-3-5-10": (
        '<p>Passwords should never travel across the network in plain text, and they should '
        'never be stored in plain text on any system. If an attacker intercepts network traffic '
        'or gains access to a password database, they should find only encrypted or hashed '
        'values — not usable credentials.</p>'
        '<p><strong>Example 1:</strong> Enforce TLS encryption on all authentication traffic. '
        'In Active Directory, enable LDAPS by installing a certificate on your domain controllers '
        '(via <em>Active Directory Certificate Services</em> or a third-party CA). Verify it is '
        'working by running <code>ldp.exe</code>, connecting to your DC on port 636 with SSL. '
        'Then disable plain LDAP (port 389) binds by configuring the registry key '
        '<code>HKLM\\System\\CurrentControlSet\\Services\\NTDS\\Parameters\\LDAPServerIntegrity</code> '
        'to require signing.</p>'
        '<p><strong>Example 2:</strong> Ensure your web applications and portals use HTTPS '
        'exclusively. In IIS Manager, select your site and go to <em>SSL Settings</em>, then '
        'check "Require SSL." For internal tools that might still use HTTP login pages, configure '
        'an HTTP-to-HTTPS redirect rule under <em>URL Rewrite</em>. On the storage side, verify '
        'that your application databases store passwords using bcrypt, scrypt, or PBKDF2 — never '
        'MD5 or SHA-1 alone.</p>'
    ),

    "ia-l2-3-5-11": (
        '<p>When someone types their password, the system should not display it on screen in '
        'plain text. This prevents "shoulder surfing" — someone nearby reading the password off '
        'your monitor. The standard approach is to show dots or asterisks instead of the actual '
        'characters.</p>'
        '<p>This applies to workstations, mobile devices, web apps, and any login prompt.</p>'
        '<p><strong>Example 1:</strong> On Windows workstations, ensure the "reveal password" '
        'button on the login screen is controlled. Via Group Policy, navigate to <em>Computer '
        'Configuration &gt; Administrative Templates &gt; Windows Components &gt; Credential '
        'User Interface</em> and set "Do not display the password reveal button" to '
        '<strong>Enabled</strong>. This removes the eye icon that lets users temporarily unmask '
        'their password on the Windows login screen.</p>'
        '<p><strong>Example 2:</strong> For custom web applications, ensure all password input '
        'fields use <code>&lt;input type="password"&gt;</code> rather than '
        '<code>&lt;input type="text"&gt;</code>. If your application includes a "show password" '
        'toggle, make sure it defaults to masked and auto-re-masks after a short timeout (e.g., '
        '3 seconds). Conduct a quick review of all login and account management pages to verify '
        'this is consistently implemented.</p>'
    ),

    # =========================================================================
    # INCIDENT RESPONSE (IR) — 3 practices
    # =========================================================================

    "ir-l2-3-6-1": (
        '<p>You need a real plan for what happens when something goes wrong — a malware '
        'infection, a phishing compromise, a data breach. This is not a plan that sits in a '
        'drawer. It is a living capability that covers preparation, detection, containment, '
        'eradication, and recovery. Everyone involved needs to know their role before an '
        'incident happens.</p>'
        '<p><strong>Example 1:</strong> Create an Incident Response Plan (IRP) document that '
        'defines roles (Incident Commander, technical lead, communications lead), contact lists, '
        'escalation procedures, and playbooks for common scenarios (ransomware, phishing, '
        'insider threat). Store it in a shared location like SharePoint under a dedicated '
        '"Security" site. Include a section that maps to NIST SP 800-61 phases: Preparation, '
        'Detection & Analysis, Containment, Eradication & Recovery, and Post-Incident Activity.</p>'
        '<p><strong>Example 2:</strong> Configure automated detection in Microsoft Defender '
        'for Endpoint. In the <em>Microsoft 365 Defender portal &gt; Settings &gt; Endpoints '
        '&gt; Advanced Features</em>, enable automated investigation and response. Set up alert '
        'notifications under <em>Settings &gt; Email Notifications</em> so your incident '
        'response team gets immediate alerts for high-severity detections. This gives you the '
        '"detection and analysis" leg of your incident handling capability running 24/7.</p>'
    ),

    "ir-l2-3-6-2": (
        '<p>When a security incident happens, you need to track it from start to finish — '
        'what happened, when, what systems were affected, who responded, and what was the '
        'outcome. You also need to report incidents up the chain promptly, both internally and '
        'to external parties if required (for CMMC, that includes DIBCAC).</p>'
        '<p><strong>Example 1:</strong> Use a ticketing system (Jira, ServiceNow, or even a '
        'dedicated tool like TheHive) to log every security incident. Create an "Incident" '
        'ticket type with required fields: date/time detected, affected systems, severity level, '
        'current status, and assigned responder. For CMMC compliance, document that cyber '
        'incidents involving CUI must be reported to DIBCAC at '
        '<code>https://dibnet.dod.mil</code> within 72 hours of discovery.</p>'
        '<p><strong>Example 2:</strong> Stand up an internal reporting channel — a dedicated '
        'email alias like <code>security@yourcompany.com</code> and a page on your intranet '
        'with simple instructions for employees: "If you see something suspicious, email '
        'security@ or call ext. 5555." In M365, you can create a shared mailbox under '
        '<em>Admin Center &gt; Teams & Groups &gt; Shared Mailboxes</em> and grant access to '
        'your IR team. This provides the "incident response support resource" the practice '
        'requires.</p>'
    ),

    "ir-l2-3-6-3": (
        '<p>Having an incident response plan is not enough — you have to test it. Run exercises '
        'to find out if your team actually knows what to do when things go sideways. A tabletop '
        'exercise where you walk through a scenario together is far better than finding out '
        'your plan does not work during a real breach.</p>'
        '<p><strong>Example 1:</strong> Conduct a tabletop exercise at least annually. Pick a '
        'realistic scenario — say, a ransomware attack that encrypts file shares containing CUI. '
        'Gather your IR team, IT staff, management, and legal. Walk through the scenario step '
        'by step: Who detects it? Who does the Incident Commander call first? How do you isolate '
        'affected systems? Where are your backups? Document the exercise, including gaps '
        'identified, and update your IRP based on lessons learned.</p>'
        '<p><strong>Example 2:</strong> Use an adversary simulation tool like Atomic Red Team '
        '(free, open-source) to test your detection capabilities. Run specific MITRE ATT&CK '
        'technique tests — for example, test T1059.001 (PowerShell execution) by running '
        '<code>Invoke-AtomicTest T1059.001</code> on a test workstation. Verify that your EDR '
        '(Defender for Endpoint, CrowdStrike, etc.) detects and alerts on the activity. If it '
        'does not, you have found a gap to fix before a real attacker exploits it.</p>'
    ),
}
